development:
  adapter: postgresql
  encoding: utf8
  database: canned_ham_development
  pool: 5
  username: david.schaaf  
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: canned_ham_test
  pool: 5
  username: david.schaaf
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: canned_ham_production
  pool: 5
  username: david.schaaf
  password:
